namespace EcoQuest;
public static class FishStrings
{
    public const string SeaTurtle = "[cyan]Role & Importance:[/] [yellow]Sea Turtles[/] play a critical role in maintaining healthy seagrass beds and coral reefs by grazing on seagrass, which helps prevent overgrowth and supports marine life. \n[cyan]How They Exist:[/] These marine reptiles migrate long distances across oceans, nesting on beaches to lay their eggs. \n[cyan]Endangered Status:[/] Sea turtles are endangered due to habitat loss, bycatch in fishing nets, pollution, and climate change, which affects their nesting sites and sex ratios. \n[cyan]Why They Are Endangered:[/] Destruction of nesting habitats, poaching for their shells and eggs, accidental capture in fishing gear, and environmental changes are major threats. \n[cyan]Conservation Efforts:[/] Protecting nesting sites, reducing bycatch, and improving waste management are key strategies to save sea turtles.";

    public const string Conch = "[cyan]Role & Importance:[/] [yellow]Conchs[/] are important herbivores in marine ecosystems, grazing on algae and helping maintain healthy reef systems. \n[cyan]How They Exist:[/] Found primarily in tropical waters, conchs live on the seafloor and are known for their beautiful spiral shells. \n[cyan]Endangered Status:[/] Certain conch species, particularly the queen conch, are endangered. Overfishing for their meat and shells, along with habitat destruction, has led to a steep population decline. \n[cyan]Why They Are Endangered:[/] Unsustainable harvesting, habitat destruction, and poor management of fishing practices have severely reduced conch populations. \n[cyan]Conservation Efforts:[/] Enforcing sustainable fishing practices and protecting critical habitats are necessary to ensure their survival.";

    public const string BluefinTuna = "[cyan]Role & Importance:[/] [yellow]Bluefin Tuna[/] are apex predators in the ocean, helping regulate the populations of smaller fish. \n[cyan]How They Exist:[/] They are highly migratory and can travel across oceans, known for their speed and endurance. \n[cyan]Endangered Status:[/] Bluefin tuna are critically endangered, particularly the Atlantic and Southern populations, due to overfishing and illegal fishing. \n[cyan]Why They Are Endangered:[/] High market demand for their meat, especially in sushi markets, has led to overfishing. Overexploitation, along with weak enforcement of fishing regulations, is pushing their numbers to dangerously low levels. \n[cyan]Conservation Efforts:[/] International quotas, sustainable fishing practices, and better enforcement of fishing laws are crucial to help populations recover.";

    public const string SlenderGrouper = "[cyan]Role & Importance:[/] [yellow]Slender Groupers[/] are important predators in coral reef ecosystems, feeding on smaller fish and crustaceans, which helps maintain ecological balance. \n[cyan]How They Exist:[/] Slender groupers are found in the Indo-Pacific region, inhabiting coral reefs and rocky seabeds. They are solitary and prefer shallow to moderately deep waters. \n[cyan]Status:[/] Slender groupers do not face significant threats and are classified as Least Concern. Their populations are stable, thriving in healthy marine environments.";


    public const string Shark = "[cyan]Role & Importance:[/] [yellow]Sharks[/] are apex predators, essential for maintaining the balance of marine ecosystems by regulating prey populations. \n[cyan]How They Exist:[/] Sharks are found in oceans worldwide and vary greatly in size, from small species to the massive whale shark. \n[cyan]Endangered Status:[/] Many shark species, such as the great white, hammerhead, and tiger shark, are endangered due to overfishing, bycatch, and finning. \n[cyan]Why They Are Endangered:[/] Overfishing, demand for shark fins, and habitat destruction have pushed shark populations to decline sharply. \n[cyan]Conservation Efforts:[/] Protecting shark habitats, regulating fishing practices, and banning shark finning are essential to their conservation.";

    public const string BlueWhale = "[cyan]Role & Importance:[/] [yellow]Blue Whales[/] are the largest animals on Earth and play a key role in the marine food chain by consuming large quantities of krill. \n[cyan]How They Exist:[/] Blue whales migrate across oceans, feeding in nutrient-rich waters and breeding in warmer seas. \n[cyan]Endangered Status:[/] Blue whales are endangered, primarily due to hunting in the past and ongoing threats from ship strikes, pollution, and climate change. \n[cyan]Why They Are Endangered:[/] Habitat disturbances, noise pollution, and the impact of climate change on krill populations still threaten their survival. \n[cyan]Conservation Efforts:[/] International protection against whaling, reducing ship collisions, and addressing ocean pollution are critical to their recovery.";

    public const string YellowfinTuna = "[cyan]Role & Importance:[/] [yellow]Yellowfin Tuna[/] are important predators in the open ocean, maintaining healthy marine food webs. \n[cyan]How They Exist:[/] Found in tropical and subtropical waters, they are migratory and a major species for commercial fishing. \n[cyan]Status:[/] Not endangered, though they face overfishing pressures, especially in certain regions. Conservation measures and regulations have helped maintain stable populations.";

    public const string Goldfish = "[cyan]Role & Importance:[/] [yellow]Goldfish[/] are primarily ornamental, often kept in aquariums and ponds, and are a key species in the pet trade. \n[cyan]How They Exist:[/] They thrive in freshwater environments and are widely distributed as pets. \n[cyan]Status:[/] Not endangered. Goldfish are domesticated and do not face the same threats as wild fish, though their invasive nature can sometimes disrupt local ecosystems.";

    public const string DoryFish = "[cyan]Role & Importance:[/] [yellow]Dory Fish (Regal Tang)[/] are herbivores, feeding on algae and helping maintain the health of coral reefs. \n[cyan]How They Exist:[/] They inhabit coral reefs and tropical waters, often found in large schools. \n[cyan]Status:[/] Not endangered, though they are popular in the aquarium trade, which can sometimes lead to unsustainable harvesting practices.";

    public const string Sardines = "[cyan]Role & Importance:[/] [yellow]Sardines[/] are crucial for marine food webs, serving as a primary food source for larger fish, sea birds, and marine mammals. \n[cyan]How They Exist:[/] Sardines are found in large schools in coastal waters. \n[cyan]Status:[/] Not endangered, though populations can fluctuate due to environmental conditions like water temperature and overfishing pressures.";

    public const string Jellyfish = "[cyan]Role & Importance:[/] [yellow]Jellyfish[/] play an important role in the marine food chain, serving as both predators and prey for various species. \n[cyan]How They Exist:[/] Jellyfish are found in oceans worldwide, thriving in a variety of marine environments. \n[cyan]Status:[/] Not endangered. In fact, some jellyfish populations have expanded due to overfishing of their predators, like certain species of fish and sea turtles.";

    public const string Pufferfish = "[cyan]Role & Importance:[/] [yellow]Pufferfish[/] serve as both prey and predator in the marine ecosystem, feeding on small invertebrates and algae. \n[cyan]How They Exist:[/] They are found in both freshwater and marine environments and are known for their ability to inflate when threatened. \n[cyan]Status:[/] Not endangered, though some species of pufferfish are threatened by habitat loss and pollution.";

    public const string Clams = "[cyan]Role & Importance:[/] [yellow]Clams[/] are filter feeders that help improve water quality by filtering out plankton and other small particles. \n[cyan]How They Exist:[/] Clams are found in both freshwater and marine environments, living on the seafloor or buried in mud. \n[cyan]Status:[/] Not endangered. Most clam species are harvested sustainably, but some local populations may face threats due to pollution and overfishing.";

    public const string MantaRays = "[cyan]Role & Importance:[/] [yellow]Manta Rays[/] are filter feeders that play an important role in controlling plankton populations. \n[cyan]How They Exist:[/] Manta rays inhabit tropical and subtropical oceans, often migrating in search of food. \n[cyan]Status:[/] Not endangered, although they are vulnerable due to accidental capture in fishing nets and habitat destruction.";

    public const string Shrimp = "[cyan]Role & Importance:[/] [yellow]Shrimp[/] play a key role in marine food chains, feeding on detritus and small organisms, and providing food for larger predators. \n[cyan]How They Exist:[/] Shrimp are found in both freshwater and marine environments, living on the seafloor or in burrows. \n[cyan]Status:[/] Not endangered, though some species are threatened by overfishing and habitat loss due to coastal development.";
    public const string Seahorse = "[cyan]Role & Importance:[/] [yellow]Seahorses[/] play a unique role in marine ecosystems as predators of small crustaceans, helping control their populations. They are also important for ecotourism and as indicators of healthy seagrass beds and coral reefs. \n[cyan]How They Exist:[/] Seahorses are small, slow-moving fish found in shallow coastal waters, often clinging to seagrass or coral using their prehensile tails. \n[cyan]Status:[/] Seahorses do not currently face significant threats and do not require tracking. Their populations are stable, and they thrive in healthy coastal environments.";

    public const string GreenMorayEel = "[cyan]Role & Importance:[/] [yellow]Green Moray Eels[/] are important predators in marine ecosystems, feeding on fish, crustaceans, and cephalopods, which helps maintain balance within the food web. \n[cyan]How They Exist:[/] Green moray eels are found in the western Atlantic Ocean, inhabiting coral reefs, rocky shorelines, and mangroves. They are nocturnal hunters and spend much of their time hiding in crevices. \n[cyan]Status:[/] Green moray eels are not considered endangered and do not face significant threats. Their populations are stable, thriving in healthy coastal ecosystems.";



}