/*
--/ Class for storing books \--

Overview:
 This class is used solely for storing books. 

Use the following format:
    new Book("Book title", "Contents of the book"),

When adding a new book:
    Add a cover image to the LibrarySystem/Covers folder.
    NOTE: It must match the title of the book!
 */

namespace EcoQuest;

public static class Books
{
    public readonly static List<Book> List = [
        new Book("Shrek!", "Listen here, Donkey! Just because I like my swamp quiet, doesn’t mean I’m not goin' to get a little company now and then. But, by the looks of it, this place is turning into a circus!\nYou know, Donkey, I’ve lived here for years, and I’ve never had to deal with half the nonsense that’s come through here since you showed up! I used to have peace and quiet, now I got a dragon and a bunch of talking animals livin' in my backyard. MY backyard!\nBut, fine, I suppose I’ve got no choice now. You’re here to stay, and... well, you’re better than that horrid prince, so you’ve got that going for you.\nAnyway, what’s for dinner?"),
        new Book("Cars", "Ka-chow! You see that, folks? That's how you make an entrance!\nI’m Lightning McQueen, the fastest race car in the world, and don't you forget it!\nYou know, when I first got here to Radiator Springs, I thought it was just some dusty little town with nothing special... but man, was I wrong!\nThese folks? They're something else! They've got heart, they've got style, and they’ve got a whole lot more than just a good paint job.\nDoc Hudson? The guy’s a legend! He’s got more knowledge in his bumper than I have in my whole engine!\nAnd Mater? Well, he's... he's got a... special kind of charm. Maybe not the sharpest tool in the shed, but he's loyal, and that's worth more than anything!\nAnyway, enough of that. The race is coming up, and I gotta focus! No distractions, no pit stops — just me, the track, and that shiny trophy waiting at the end!\nBut hey, if I need a little help, I know I can count on my friends.\nAlright, time to get back to training. Let's hit it, Mater!"),
        new Book("My Little Pony", "It was a sunny day in Ponyville, and Twilight Sparkle was busy organizing the library when Spike rushed in, holding a scroll.\n\"Twilight! Look at this!\" Spike exclaimed, unrolling the parchment.\nThe letter was from Princess Celestia, inviting Twilight and her friends to Canterlot to help with an urgent problem.\n\"The royal gardens are in trouble!\" Twilight read aloud. \"The magical flowers are wilting, and nopony knows why!\"\n\nThe Mane Six gathered quickly and boarded the Friendship Express, brainstorming solutions along the way.\nWhen they arrived, Princess Celestia greeted them with a worried expression.\n\"I fear the Harmony Blossoms are losing their magic,\" she explained. \"Without them, the balance of nature in Equestria could be at risk.\"\n\nFluttershy suggested checking the soil, while Applejack offered to test the watering system.\nRainbow Dash zoomed overhead, scouting for weather-related issues, and Rarity examined the blossoms for any unusual signs.\nMeanwhile, Pinkie Pie distracted the royal gardeners with cheerful songs and cupcakes to lift their spirits.\n\nAfter hours of investigation, Twilight discovered the problem: a mischievous group of breezies had accidentally taken too much pollen, upsetting the balance of the flowers' magic.\n\"Don't worry,\" Fluttershy said gently, coaxing the breezies to return the pollen. \"It was an honest mistake.\"\n\nWith the breezies' help, the flowers regained their magic, blooming brighter than ever.\nPrincess Celestia beamed with gratitude.\n\"Once again, you've shown the power of friendship and teamwork,\" she said.\n\nAs the sun set, the ponies returned to Ponyville, feeling proud of their efforts.\n\"And now,\" Pinkie Pie giggled, \"we celebrate with a 'Saved the Garden' party!\"\n\nEverypony laughed, knowing that together, they could overcome any challenge.\n"),
        new Book("Overfishing","Overfishing occurs when fish are removed from the ocean faster than they can naturally reproduce, leading to the depletion of fish populations.\nThis problem is primarily caused by high demand for seafood, unregulated fishing practices, and the use of destructive fishing methods.\nOverfishing doesn’t just affect fish populations, it disrupts entire marine ecosystems and threatens food security for millions of people.\nTo combat overfishing, implementing fishing quotas, enforcing sustainable fishing practices, and supporting marine protected areas are crucial steps.\nMonitoring fish species is equally important as it helps ensure sustainable fish populations and maintains the balance of ocean ecosystems.\nWithout proper management, species can dwindle not only from overfishing but also from habitat destruction, climate change, and pollution.\nWe must also remember the cascading effects of overfishing.\nThe loss of one species can impact predator-prey relationships, leading to further imbalances.\nEveryone has a role to play, from governments creating regulations to individuals choosing sustainably sourced seafood.\nProtecting our oceans today ensures marine biodiversity and resources for future generations.\n"),
        new Book("Coastal Pollution", "Coastal pollution is a significant environmental issue that impacts marine ecosystems and communities worldwide.\nIt primarily results from improper waste disposal, agricultural runoff, and industrial discharges,\nwhich introduce harmful substances like plastics, chemicals, and excess nutrients into coastal waters.\nThis pollution disrupts marine habitats, harms biodiversity, and contaminates food sources, affecting both aquatic life and human health.\nPreventing coastal pollution involves reducing plastic usage, improving waste management, and adopting sustainable agricultural practices.\nProtecting our coasts benefits marine life, enhances water quality, and supports livelihoods reliant on healthy oceans.\nWithout action, polluted waters can lead to dead zones, coral bleaching, and declines in fish populations.\nCoastal pollution is a major focus of SDG Goal 14, emphasizing the need to conserve and sustainably use ocean resources.\nSimple actions, like participating in beach cleanups and reducing single-use plastics, can make a big difference.\nAddressing coastal pollution is essential for preserving the oceans and ensuring a sustainable future for all life on Earth.\n"),
    ];
}