namespace EcoQuest;

public static class Books
{
    public readonly static List<Book> List = [
        new Book("Shrek!", "Listen here, Donkey! Just because I like my swamp quiet, doesn’t mean I’m not goin' to get a little company now and then. But, by the looks of it, this place is turning into a circus!\nYou know, Donkey, I’ve lived here for years, and I’ve never had to deal with half the nonsense that’s come through here since you showed up! I used to have peace and quiet, now I got a dragon and a bunch of talking animals livin' in my backyard. MY backyard!\nBut, fine, I suppose I’ve got no choice now. You’re here to stay, and... well, you’re better than that horrid prince, so you’ve got that going for you.\nAnyway, what’s for dinner?"),
        new Book("Cars", "Ka-chow! You see that, folks? That's how you make an entrance!\nI’m Lightning McQueen, the fastest race car in the world, and don't you forget it!\nYou know, when I first got here to Radiator Springs, I thought it was just some dusty little town with nothing special... but man, was I wrong!\nThese folks? They're something else! They've got heart, they've got style, and they’ve got a whole lot more than just a good paint job.\nDoc Hudson? The guy’s a legend! He’s got more knowledge in his bumper than I have in my whole engine!\nAnd Mater? Well, he's... he's got a... special kind of charm. Maybe not the sharpest tool in the shed, but he's loyal, and that's worth more than anything!\nAnyway, enough of that. The race is coming up, and I gotta focus! No distractions, no pit stops — just me, the track, and that shiny trophy waiting at the end!\nBut hey, if I need a little help, I know I can count on my friends.\nAlright, time to get back to training. Let's hit it, Mater!"),
        new Book("My Little Pony", "It was a sunny day in Ponyville, and Twilight Sparkle was busy organizing the library when Spike rushed in, holding a scroll.\n\"Twilight! Look at this!\" Spike exclaimed, unrolling the parchment.\nThe letter was from Princess Celestia, inviting Twilight and her friends to Canterlot to help with an urgent problem.\n\"The royal gardens are in trouble!\" Twilight read aloud. \"The magical flowers are wilting, and nopony knows why!\"\n\nThe Mane Six gathered quickly and boarded the Friendship Express, brainstorming solutions along the way.\nWhen they arrived, Princess Celestia greeted them with a worried expression.\n\"I fear the Harmony Blossoms are losing their magic,\" she explained. \"Without them, the balance of nature in Equestria could be at risk.\"\n\nFluttershy suggested checking the soil, while Applejack offered to test the watering system.\nRainbow Dash zoomed overhead, scouting for weather-related issues, and Rarity examined the blossoms for any unusual signs.\nMeanwhile, Pinkie Pie distracted the royal gardeners with cheerful songs and cupcakes to lift their spirits.\n\nAfter hours of investigation, Twilight discovered the problem: a mischievous group of breezies had accidentally taken too much pollen, upsetting the balance of the flowers' magic.\n\"Don't worry,\" Fluttershy said gently, coaxing the breezies to return the pollen. \"It was an honest mistake.\"\n\nWith the breezies' help, the flowers regained their magic, blooming brighter than ever.\nPrincess Celestia beamed with gratitude.\n\"Once again, you've shown the power of friendship and teamwork,\" she said.\n\nAs the sun set, the ponies returned to Ponyville, feeling proud of their efforts.\n\"And now,\" Pinkie Pie giggled, \"we celebrate with a 'Saved the Garden' party!\"\n\nEverypony laughed, knowing that together, they could overcome any challenge.\n")
        
    ];
}